# Covid-19 Data Analysis Using Problem Statements

# Import Libraries

In [1]:
import numpy as np
import pandas as pd

# Data Loading

In [2]:
covid = pd.read_csv(r"C:\Users\Kajal\Desktop\ssd\Desktop\dataset work November\datasets\COVID\country_wise_latest.csv")
covid

,Country/Region,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,Deaths / 100 Cases,Recovered / 100 Cases,Deaths / 100 Recovered,Confirmed last week,1 week change,1 week % increase,WHO Region
0,Afghanistan,36263,1269,25198,9796,106,10,18,3.50,69.49,5.04,35526,737,2.07,Eastern Mediterranean
1,Albania,4880,144,2745,1991,117,6,63,2.95,56.25,5.25,4171,709,17.00,Europe
2,Algeria,27973,1163,18837,7973,616,8,749,4.16,67.34,6.17,23691,4282,18.07,Africa
3,Andorra,907,52,803,52,10,0,0,5.73,88.53,6.48,884,23,2.60,Europe
4,Angola,950,41,242,667,18,1,0,4.32,25.47,16.94,749,201,26.84,Africa
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182,West Bank and Gaza,10621,78,3752,6791,152,2,0,0.73,35.33,2.08,8916,1705,19.12,Eastern Mediterranean
183,Western Sahara,10,1,8,1,0,0,0,10.00,80.00,12.50,10,0,0.00,Africa
184,Yemen,1691,483,833,375,10,4,36,28.56,49.26,57.98,1619,72,4.45,Eastern Mediterranean
185,Zambia,4552,140,2815,1597,71,1,465,3.08,61.84,4.97,3326,1226,36.86,Africa
186,Zimbabwe,2704,36,542,2126,192,2,24,1.33,20.04,6.64,1713,991,57.85,Africa

# info

In [3]:
covid.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 187 entries, 0 to 186
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Country/Region          187 non-null    object
 1   Confirmed               187 non-null    int64
 2   Deaths                  187 non-null    int64
 3   Recovered               187 non-null    int64
 4   Active                  187 non-null    int64
 5   New cases               187 non-null    int64
 6   New deaths              187 non-null    int64
 7   New recovered           187 non-null    int64
 8   Deaths / 100 Cases      187 non-null    float64
 9   Recovered / 100 Cases   187 non-null    float64
 10  Deaths / 100 Recovered  187 non-null    float64
 11  Confirmed last week     187 non-null    int64
 12  1 week change           187 non-null    int64
 13  1 week % increase       187 non-null    float64
 14  WHO Region              187 non-null    object
dtypes: float64(4), int64(9), object(2)
memory usage: 22.0+ KB

# describe

In [4]:
covid.describe()

,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,Deaths / 100 Cases,Recovered / 100 Cases,Deaths / 100 Recovered,Confirmed last week,1 week change,1 week % increase
count,1.870000e+02,187.000000,1.870000e+02,1.870000e+02,187.000000,187.000000,187.000000,187.000000,187.000000,187.000000,1.870000e+02,187.000000,187.000000
mean,8.813094e+04,3497.518717,5.063148e+04,3.400194e+04,1222.957219,28.957219,933.812834,3.019519,64.820535,39.473850,7.868248e+04,9448.459893,13.606203
std,3.833187e+05,14100.002482,1.901882e+05,2.133262e+05,5710.374790,120.037173,4197.719635,3.454302,26.287694,332.178192,3.382737e+05,47491.127684,24.509838
min,1.000000e+01,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000e+01,-47.000000,-3.840000
25%,1.114000e+03,18.500000,6.265000e+02,1.415000e+02,4.000000,0.000000,0.000000,0.945000,48.770000,1.295000,1.051500e+03,49.000000,2.775000
50%,5.059000e+03,108.000000,2.815000e+03,1.600000e+03,49.000000,1.000000,22.000000,2.150000,71.320000,3.510000,5.020000e+03,432.000000,6.890000
75%,4.046050e+04,734.000000,2.260600e+04,9.149000e+03,419.500000,6.000000,221.000000,3.875000,86.885000,6.190000,3.708050e+04,3172.000000,16.855000
max,4.290259e+06,148011.000000,1.846641e+06,2.816444e+06,56336.000000,1076.000000,33728.000000,28.560000,100.000000,3259.260000,3.834677e+06,455582.000000,226.320000

# checking null values

In [5]:
covid.isnull().any()

Country/Region            False
Confirmed                 False
Deaths                    False
Recovered                 False
Active                    False
New cases                 False
New deaths                False
New recovered             False
Deaths / 100 Cases        False
Recovered / 100 Cases     False
Deaths / 100 Recovered    False
Confirmed last week       False
1 week change             False
1 week % increase         False
WHO Region                False
dtype: bool

In [6]:
covid.isnull().sum()

Country/Region            0
Confirmed                 0
Deaths                    0
Recovered                 0
Active                    0
New cases                 0
New deaths                0
New recovered             0
Deaths / 100 Cases        0
Recovered / 100 Cases     0
Deaths / 100 Recovered    0
Confirmed last week       0
1 week change             0
1 week % increase         0
WHO Region                0
dtype: int64

# Q.1 Calculate the count of Countries And WHO Regions

# 1. Countries

In [7]:
covid["Country/Region"].count()

187

In [8]:
covid["Country/Region"].unique()

array(['Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola',
       'Antigua and Barbuda', 'Argentina', 'Armenia', 'Australia',
       'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh',
       'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bhutan',
       'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil',
       'Brunei', 'Bulgaria', 'Burkina Faso', 'Burma', 'Burundi',
       'Cabo Verde', 'Cambodia', 'Cameroon', 'Canada',
       'Central African Republic', 'Chad', 'Chile', 'China', 'Colombia',
       'Comoros', 'Congo (Brazzaville)', 'Congo (Kinshasa)', 'Costa Rica',
       "Cote d'Ivoire", 'Croatia', 'Cuba', 'Cyprus', 'Czechia', 'Denmark',
       'Djibouti', 'Dominica', 'Dominican Republic', 'Ecuador', 'Egypt',
       'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia',
       'Eswatini', 'Ethiopia', 'Fiji', 'Finland', 'France', 'Gabon',
       'Gambia', 'Georgia', 'Germany', 'Ghana', 'Greece', 'Greenland',
       'Grenada', 'Guatemala', 'Guinea', 'Guinea-Bissau', 'Guyana',
       'Haiti', 'Holy See', 'Honduras', 'Hungary', 'Iceland', 'India',
       'Indonesia', 'Iran', 'Iraq', 'Ireland', 'Israel', 'Italy',
       'Jamaica', 'Japan', 'Jordan', 'Kazakhstan', 'Kenya', 'Kosovo',
       'Kuwait', 'Kyrgyzstan', 'Laos', 'Latvia', 'Lebanon', 'Lesotho',
       'Liberia', 'Libya', 'Liechtenstein', 'Lithuania', 'Luxembourg',
       'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta',
       'Mauritania', 'Mauritius', 'Mexico', 'Moldova', 'Monaco',
       'Mongolia', 'Montenegro', 'Morocco', 'Mozambique', 'Namibia',
       'Nepal', 'Netherlands', 'New Zealand', 'Nicaragua', 'Niger',
       'Nigeria', 'North Macedonia', 'Norway', 'Oman', 'Pakistan',
       'Panama', 'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines',
       'Poland', 'Portugal', 'Qatar', 'Romania', 'Russia', 'Rwanda',
       'Saint Kitts and Nevis', 'Saint Lucia',
       'Saint Vincent and the Grenadines', 'San Marino',
       'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia',
       'Seychelles', 'Sierra Leone', 'Singapore', 'Slovakia', 'Slovenia',
       'Somalia', 'South Africa', 'South Korea', 'South Sudan', 'Spain',
       'Sri Lanka', 'Sudan', 'Suriname', 'Sweden', 'Switzerland', 'Syria',
       'Taiwan*', 'Tajikistan', 'Tanzania', 'Thailand', 'Timor-Leste',
       'Togo', 'Trinidad and Tobago', 'Tunisia', 'Turkey', 'US', 'Uganda',
       'Ukraine', 'United Arab Emirates', 'United Kingdom', 'Uruguay',
       'Uzbekistan', 'Venezuela', 'Vietnam', 'West Bank and Gaza',
       'Western Sahara', 'Yemen', 'Zambia', 'Zimbabwe'], dtype=object)

# 2. WHO Regions

In [9]:
covid["WHO Region"].count()

187

In [10]:
covid["WHO Region"].unique()

array(['Eastern Mediterranean', 'Europe', 'Africa', 'Americas',
       'Western Pacific', 'South-East Asia'], dtype=object)

In [11]:
covid["WHO Region"].value_counts()

Europe                   56
Africa                   48
Americas                 35
Eastern Mediterranean    22
Western Pacific          16
South-East Asia          10
Name: WHO Region, dtype: int64

# Q.2 Find the Afghanistan Confirmed cases,Deaths,Recovered cases & Active             cases data

In [12]:
afg = covid.loc[(covid["Country/Region"]=="Afghanistan")]

In [13]:
afg_1=afg[["Country/Region","Confirmed","Deaths","Recovered","Active"]]
afg_1

  Country/Region  Confirmed  Deaths  Recovered  Active
0    Afghanistan      36263    1269      25198    9796

# And also find Afghanistan New Cases, New Deaths and New Recovered cases

In [14]:
afg_new = afg[["Country/Region","New cases","New deaths","New recovered"]]
afg_new

  Country/Region  New cases  New deaths  New recovered
0    Afghanistan        106          10             18

# Q.3 Find Europe data and also find Europe under countries count

In [15]:
Eup = covid.loc[(covid["WHO Region"]=="Europe")]

In [16]:
Eup

,Country/Region,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,Deaths / 100 Cases,Recovered / 100 Cases,Deaths / 100 Recovered,Confirmed last week,1 week change,1 week % increase,WHO Region
1,Albania,4880,144,2745,1991,117,6,63,2.95,56.25,5.25,4171,709,17.00,Europe
3,Andorra,907,52,803,52,10,0,0,5.73,88.53,6.48,884,23,2.60,Europe
7,Armenia,37390,711,26665,10014,73,6,187,1.90,71.32,2.67,34981,2409,6.89,Europe
9,Austria,20558,713,18246,1599,86,1,37,3.47,88.75,3.91,19743,815,4.13,Europe
10,Azerbaijan,30446,423,23242,6781,396,6,558,1.39,76.34,1.82,27890,2556,9.16,Europe
15,Belarus,67251,538,60492,6221,119,4,67,0.80,89.95,0.89,66213,1038,1.57,Europe
16,Belgium,66428,9822,17452,39154,402,1,14,14.79,26.27,56.28,64094,2334,3.64,Europe
21,Bosnia and Herzegovina,10498,294,4930,5274,731,14,375,2.80,46.96,5.96,8479,2019,23.81,Europe
25,Bulgaria,10621,347,5585,4689,194,7,230,3.27,52.58,6.21,8929,1692,18.95,Europe
43,Croatia,4881,139,3936,806,24,3,70,2.85,80.64,3.53,4370,511,11.69,Europe
45,Cyprus,1060,19,852,189,3,0,0,1.79,80.38,2.23,1038,22,2.12,Europe
46,Czechia,15516,373,11428,3715,192,2,0,2.40,73.65,3.26,14098,1418,10.06,Europe
47,Denmark,13761,613,12605,543,109,0,77,4.45,91.60,4.86,13453,308,2.29,Europe
56,Estonia,2034,69,1923,42,0,0,1,3.39,94.54,3.59,2021,13,0.64,Europe
60,Finland,7398,329,6920,149,5,0,0,4.45,93.54,4.75,7340,58,0.79,Europe
61,France,220352,30212,81212,108928,2551,17,267,13.71,36.86,37.20,214023,6329,2.96,Europe
64,Georgia,1137,16,922,199,6,0,2,1.41,81.09,1.74,1039,98,9.43,Europe
65,Germany,207112,9125,190314,7673,445,1,259,4.41,91.89,4.79,203325,3787,1.86,Europe
67,Greece,4227,202,1374,2651,34,0,0,4.78,32.51,14.70,4012,215,5.36,Europe
68,Greenland,14,0,13,1,1,0,0,0.00,92.86,0.00,13,1,7.69,Europe
75,Holy See,12,0,12,0,0,0,0,0.00,100.00,0.00,12,0,0.00,Europe
77,Hungary,4448,596,3329,523,13,0,0,13.40,74.84,17.90,4339,109,2.51,Europe
78,Iceland,1854,10,1823,21,7,0,0,0.54,98.33,0.55,1839,15,0.82,Europe
83,Ireland,25892,1764,23364,764,11,0,0,6.81,90.24,7.55,25766,126,0.49,Europe
84,Israel,63985,474,27133,36378,2029,4,108,0.74,42.41,1.75,52003,11982,23.04,Europe
85,Italy,246286,35112,198593,12581,168,5,147,14.26,80.64,17.68,244624,1662,0.68,Europe
89,Kazakhstan,84648,585,54404,29659,1526,0,1833,0.69,64.27,1.08,73468,11180,15.22,Europe
91,Kosovo,7413,185,4027,3201,496,16,274,2.50,54.32,4.59,5877,1536,26.14,Europe
93,Kyrgyzstan,33296,1301,21205,10790,483,24,817,3.91,63.69,6.14,27143,6153,22.67,Europe
95,Latvia,1219,31,1045,143,0,0,0,2.54,85.73,2.97,1192,27,2.27,Europe
100,Liechtenstein,86,1,81,4,0,0,0,1.16,94.19,1.23,86,0,0.00,Europe
101,Lithuania,2019,80,1620,319,11,0,4,3.96,80.24,4.94,1947,72,3.70,Europe
102,Luxembourg,6321,112,4825,1384,49,0,178,1.77,76.33,2.32,5639,682,12.09,Europe
108,Malta,701,9,665,27,1,0,0,1.28,94.86,1.35,677,24,3.55,Europe
112,Moldova,23154,748,16154,6252,120,13,245,3.23,69.77,4.63,21115,2039,9.66,Europe
113,Monaco,116,4,104,8,0,0,0,3.45,89.66,3.85,109,7,6.42,Europe
115,Montenegro,2893,45,809,2039,94,2,70,1.56,27.96,5.56,2188,705,32.22,Europe
120,Netherlands,53413,6160,189,47064,419,1,0,11.53,0.35,3259.26,52132,1281,2.46,Europe
125,North Macedonia,10213,466,5564,4183,127,6,137,4.56,54.48,8.38,9249,964,10.42,Europe
126,Norway,9132,255,8752,125,15,0,0,2.79,95.84,2.91,9034,98,1.08,Europe
134,Poland,43402,1676,32856,8870,337,5,103,3.86,75.70,5.10,40383,3019,7.48,Europe
135,Portugal,50299,1719,35375,13205,135,2,158,3.42,70.33,4.86,48771,1528,3.13,Europe
137,Romania,45902,2206,25794,17902,1104,19,151,4.81,56.19,8.55,38139,7763,20.35,Europe
138,Russia,816680,13334,602249,201097,5607,85,3077,1.63,73.74,2.21,776212,40468,5.21,Europe
143,San Marino,699,42,657,0,0,0,0,6.01,93.99,6.39,699,0,0.00,Europe
147,Serbia,24141,543,0,23598,411,9,0,2.25,0.00,0.00,21253,2888,13.59,Europe
151,Slovakia,2181,28,1616,537,2,0,39,1.28,74.09,1.73,1980,201,10.15,Europe
152,Slovenia,2087,116,1733,238,5,0,55,5.56,83.04,6.69,1953,134,6.86,Europe
157,Spain,272421,28432,150376,93613,0,0,0,10.44,55.20,18.91,264836,7585,2.86,Europe
161,Sweden,79395,5700,0,73695,398,3,0,7.18,0.00,0.00,78048,1347,1.73,Europe
162,Switzerland,34477,1978,30900,1599,65,1,200,5.74,89.62,6.40,33634,843,2.51,Europe
165,Tajikistan,7235,60,6028,1147,43,1,58,0.83,83.32,1.00,6921,314,4.54,Europe
172,Turkey,227019,5630,210469,10920,919,17,982,2.48,92.71,2.67,220572,6447,2.92,Europe
175,Ukraine,67096,1636,37202,28258,835,11,317,2.44,55.45,4.40,60767,6329,10.42,Europe
177,United Kingdom,301708,45844,1437,254427,688,7,3,15.19,0.48,3190.26,296944,4764,1.60,Europe
179,Uzbekistan,21209,121,11674,9414,678,5,569,0.57,55.04,1.04,17149,4060,23.67,Europe

# Europe Under Coutries Count

In [17]:
Eup["Country/Region"].count()

56

# Q.4 Slice the Africa data and find the Deaths / 100 Cases, Recovered / 100 Cases, Deaths / 100 Recovered

In [18]:
Afr = covid.loc[(covid["WHO Region"]=="Africa")]
Afr

,Country/Region,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,Deaths / 100 Cases,Recovered / 100 Cases,Deaths / 100 Recovered,Confirmed last week,1 week change,1 week % increase,WHO Region
2,Algeria,27973,1163,18837,7973,616,8,749,4.16,67.34,6.17,23691,4282,18.07,Africa
4,Angola,950,41,242,667,18,1,0,4.32,25.47,16.94,749,201,26.84,Africa
18,Benin,1770,35,1036,699,0,0,0,1.98,58.53,3.38,1602,168,10.49,Africa
22,Botswana,739,2,63,674,53,1,11,0.27,8.53,3.17,522,217,41.57,Africa
26,Burkina Faso,1100,53,926,121,14,0,6,4.82,84.18,5.72,1065,35,3.29,Africa
28,Burundi,378,1,301,76,17,0,22,0.26,79.63,0.33,322,56,17.39,Africa
29,Cabo Verde,2328,22,1550,756,21,0,103,0.95,66.58,1.42,2071,257,12.41,Africa
31,Cameroon,17110,391,14539,2180,402,6,0,2.29,84.97,2.69,16157,953,5.90,Africa
33,Central African Republic,4599,59,1546,2994,0,0,0,1.28,33.62,3.82,4548,51,1.12,Africa
34,Chad,922,75,810,37,7,0,0,8.13,87.85,9.26,889,33,3.71,Africa
38,Comoros,354,7,328,19,0,0,0,1.98,92.66,2.13,334,20,5.99,Africa
39,Congo (Brazzaville),3200,54,829,2317,162,3,73,1.69,25.91,6.51,2851,349,12.24,Africa
40,Congo (Kinshasa),8844,208,5700,2936,13,4,190,2.35,64.45,3.65,8443,401,4.75,Africa
42,Cote d'Ivoire,15655,96,10361,5198,59,0,183,0.61,66.18,0.93,14312,1343,9.38,Africa
54,Equatorial Guinea,3071,51,842,2178,0,0,0,1.66,27.42,6.06,3071,0,0.00,Africa
55,Eritrea,265,0,191,74,2,0,2,0.00,72.08,0.00,251,14,5.58,Africa
57,Eswatini,2316,34,1025,1257,109,2,39,1.47,44.26,3.32,1826,490,26.83,Africa
58,Ethiopia,14547,228,6386,7933,579,5,170,1.57,43.90,3.57,10207,4340,42.52,Africa
62,Gabon,7189,49,4682,2458,205,0,219,0.68,65.13,1.05,6433,756,11.75,Africa
63,Gambia,326,8,66,252,49,2,6,2.45,20.25,12.12,112,214,191.07,Africa
66,Ghana,33624,168,29801,3655,655,0,307,0.50,88.63,0.56,28430,5194,18.27,Africa
71,Guinea,7055,45,6257,753,47,2,105,0.64,88.69,0.72,6590,465,7.06,Africa
72,Guinea-Bissau,1954,26,803,1125,0,0,0,1.33,41.10,3.24,1949,5,0.26,Africa
90,Kenya,17975,285,7833,9857,372,5,90,1.59,43.58,3.64,13771,4204,30.53,Africa
97,Lesotho,505,12,128,365,0,0,0,2.38,25.35,9.38,359,146,40.67,Africa
98,Liberia,1167,72,646,449,5,0,5,6.17,55.36,11.15,1107,60,5.42,Africa
103,Madagascar,9690,91,6260,3339,395,6,681,0.94,64.60,1.45,7153,2537,35.47,Africa
104,Malawi,3664,99,1645,1920,24,0,6,2.70,44.90,6.02,2992,672,22.46,Africa
107,Mali,2513,124,1913,476,3,1,2,4.93,76.12,6.48,2475,38,1.54,Africa
109,Mauritania,6208,156,4653,1399,37,0,223,2.51,74.95,3.35,5923,285,4.81,Africa
110,Mauritius,344,10,332,2,0,0,0,2.91,96.51,3.01,343,1,0.29,Africa
117,Mozambique,1701,11,0,1690,32,0,0,0.65,0.00,0.00,1507,194,12.87,Africa
118,Namibia,1843,8,101,1734,68,0,26,0.43,5.48,7.92,1344,499,37.13,Africa
123,Niger,1132,69,1027,36,0,0,0,6.10,90.72,6.72,1105,27,2.44,Africa
124,Nigeria,41180,860,18203,22117,648,2,829,2.09,44.20,4.72,37225,3955,10.62,Africa
139,Rwanda,1879,5,975,899,58,0,57,0.27,51.89,0.51,1629,250,15.35,Africa
144,Sao Tome and Principe,865,14,734,117,2,0,38,1.62,84.86,1.91,746,119,15.95,Africa
146,Senegal,9764,194,6477,3093,83,3,68,1.99,66.34,3.00,8948,816,9.12,Africa
148,Seychelles,114,0,39,75,0,0,0,0.00,34.21,0.00,108,6,5.56,Africa
149,Sierra Leone,1783,66,1317,400,0,0,4,3.70,73.86,5.01,1711,72,4.21,Africa
154,South Africa,452529,7067,274925,170537,7096,298,9848,1.56,60.75,2.57,373628,78901,21.12,Africa
156,South Sudan,2305,46,1175,1084,43,1,0,2.00,50.98,3.91,2211,94,4.25,Africa
166,Tanzania,509,21,183,305,0,0,0,4.13,35.95,11.48,509,0,0.00,Africa
169,Togo,874,18,607,249,6,0,8,2.06,69.45,2.97,783,91,11.62,Africa
174,Uganda,1128,2,986,140,13,0,4,0.18,87.41,0.20,1069,59,5.52,Africa
183,Western Sahara,10,1,8,1,0,0,0,10.00,80.00,12.50,10,0,0.00,Africa
185,Zambia,4552,140,2815,1597,71,1,465,3.08,61.84,4.97,3326,1226,36.86,Africa
186,Zimbabwe,2704,36,542,2126,192,2,24,1.33,20.04,6.64,1713,991,57.85,Africa

In [19]:
Afr_1 = Afr[["Deaths / 100 Cases","Recovered / 100 Cases","Deaths / 100 Recovered","WHO Region"]]
Afr_1

,Deaths / 100 Cases,Recovered / 100 Cases,Deaths / 100 Recovered,WHO Region
2,4.16,67.34,6.17,Africa
4,4.32,25.47,16.94,Africa
18,1.98,58.53,3.38,Africa
22,0.27,8.53,3.17,Africa
26,4.82,84.18,5.72,Africa
28,0.26,79.63,0.33,Africa
29,0.95,66.58,1.42,Africa
31,2.29,84.97,2.69,Africa
33,1.28,33.62,3.82,Africa
34,8.13,87.85,9.26,Africa
38,1.98,92.66,2.13,Africa
39,1.69,25.91,6.51,Africa
40,2.35,64.45,3.65,Africa
42,0.61,66.18,0.93,Africa
54,1.66,27.42,6.06,Africa
55,0.00,72.08,0.00,Africa
57,1.47,44.26,3.32,Africa
58,1.57,43.90,3.57,Africa
62,0.68,65.13,1.05,Africa
63,2.45,20.25,12.12,Africa
66,0.50,88.63,0.56,Africa
71,0.64,88.69,0.72,Africa
72,1.33,41.10,3.24,Africa
90,1.59,43.58,3.64,Africa
97,2.38,25.35,9.38,Africa
98,6.17,55.36,11.15,Africa
103,0.94,64.60,1.45,Africa
104,2.70,44.90,6.02,Africa
107,4.93,76.12,6.48,Africa
109,2.51,74.95,3.35,Africa
110,2.91,96.51,3.01,Africa
117,0.65,0.00,0.00,Africa
118,0.43,5.48,7.92,Africa
123,6.10,90.72,6.72,Africa
124,2.09,44.20,4.72,Africa
139,0.27,51.89,0.51,Africa
144,1.62,84.86,1.91,Africa
146,1.99,66.34,3.00,Africa
148,0.00,34.21,0.00,Africa
149,3.70,73.86,5.01,Africa
154,1.56,60.75,2.57,Africa
156,2.00,50.98,3.91,Africa
166,4.13,35.95,11.48,Africa
169,2.06,69.45,2.97,Africa
174,0.18,87.41,0.20,Africa
183,10.00,80.00,12.50,Africa
185,3.08,61.84,4.97,Africa
186,1.33,20.04,6.64,Africa

# And also find africa Confirmed last week cases, 1 week change cases, 1 week % increase cases

In [20]:
Afr_2 = Afr[["Confirmed last week","1 week change","1 week % increase","WHO Region"]]

In [21]:
Afr_2

     Confirmed last week  1 week change  1 week % increase WHO Region
2                  23691           4282              18.07     Africa
4                    749            201              26.84     Africa
18                  1602            168              10.49     Africa
22                   522            217              41.57     Africa
26                  1065             35               3.29     Africa
28                   322             56              17.39     Africa
29                  2071            257              12.41     Africa
31                 16157            953               5.90     Africa
33                  4548             51               1.12     Africa
34                   889             33               3.71     Africa
38                   334             20               5.99     Africa
39                  2851            349              12.24     Africa
40                  8443            401               4.75     Africa
42                 14312           1343               9.38     Africa
54                  3071              0               0.00     Africa
55                   251             14               5.58     Africa
57                  1826            490              26.83     Africa
58                 10207           4340              42.52     Africa
62                  6433            756              11.75     Africa
63                   112            214             191.07     Africa
66                 28430           5194              18.27     Africa
71                  6590            465               7.06     Africa
72                  1949              5               0.26     Africa
90                 13771           4204              30.53     Africa
97                   359            146              40.67     Africa
98                  1107             60               5.42     Africa
103                 7153           2537              35.47     Africa
104                 2992            672              22.46     Africa
107                 2475             38               1.54     Africa
109                 5923            285               4.81     Africa
110                  343              1               0.29     Africa
117                 1507            194              12.87     Africa
118                 1344            499              37.13     Africa
123                 1105             27               2.44     Africa
124                37225           3955              10.62     Africa
139                 1629            250              15.35     Africa
144                  746            119              15.95     Africa
146                 8948            816               9.12     Africa
148                  108              6               5.56     Africa
149                 1711             72               4.21     Africa
154               373628          78901              21.12     Africa
156                 2211             94               4.25     Africa
166                  509              0               0.00     Africa
169                  783             91              11.62     Africa
174                 1069             59               5.52     Africa
183                   10              0               0.00     Africa
185                 3326           1226              36.86     Africa
186                 1713            991              57.85     Africa