# Artificial Neural Network

# Import Libraries

In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf

# Data Load

In [2]:
heart = pd.read_csv(r"C:\Users\Kajal\Desktop\ssd\Desktop\dataset work November\datasets\heart.csv")
heart

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,1
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,1
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,1
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,1
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up,0

# info

In [3]:
heart.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             918 non-null    int64
 1   Sex             918 non-null    object
 2   ChestPainType   918 non-null    object
 3   RestingBP       918 non-null    int64
 4   Cholesterol     918 non-null    int64
 5   FastingBS       918 non-null    int64
 6   RestingECG      918 non-null    object
 7   MaxHR           918 non-null    int64
 8   ExerciseAngina  918 non-null    object
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    object
 11  HeartDisease    918 non-null    int64
dtypes: float64(1), int64(6), object(5)
memory usage: 86.2+ KB

# describe

In [4]:
heart.describe()

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease
count,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000
mean,53.510893,132.396514,198.799564,0.233115,136.809368,0.887364,0.553377
std,9.432617,18.514154,109.384145,0.423046,25.460334,1.066570,0.497414
min,28.000000,0.000000,0.000000,0.000000,60.000000,-2.600000,0.000000
25%,47.000000,120.000000,173.250000,0.000000,120.000000,0.000000,0.000000
50%,54.000000,130.000000,223.000000,0.000000,138.000000,0.600000,1.000000
75%,60.000000,140.000000,267.000000,0.000000,156.000000,1.500000,1.000000
max,77.000000,200.000000,603.000000,1.000000,202.000000,6.200000,1.000000

# check null values

In [5]:
heart.isnull().any()

Age               False
Sex               False
ChestPainType     False
RestingBP         False
Cholesterol       False
FastingBS         False
RestingECG        False
MaxHR             False
ExerciseAngina    False
Oldpeak           False
ST_Slope          False
HeartDisease      False
dtype: bool

In [6]:
heart.isnull().sum()

Age               0
Sex               0
ChestPainType     0
RestingBP         0
Cholesterol       0
FastingBS         0
RestingECG        0
MaxHR             0
ExerciseAngina    0
Oldpeak           0
ST_Slope          0
HeartDisease      0
dtype: int64

# Label Encoding (Convert data string to numeric)

In [7]:
from sklearn.preprocessing import LabelEncoder
L1 = LabelEncoder()
heart["Sex"] = L1.fit_transform(heart["Sex"])
heart["ChestPainType"] = L1.fit_transform(heart["ChestPainType"])
heart["RestingECG"] = L1.fit_transform(heart["RestingECG"])
heart["ExerciseAngina"] = L1.fit_transform(heart["ExerciseAngina"])
heart["ST_Slope"] = L1.fit_transform(heart["ST_Slope"])

In [8]:
heart

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,1,1,140,289,0,1,172,0,0.0,2,0
1,49,0,2,160,180,0,1,156,0,1.0,1,1
2,37,1,1,130,283,0,2,98,0,0.0,2,0
3,48,0,0,138,214,0,1,108,1,1.5,1,1
4,54,1,2,150,195,0,1,122,0,0.0,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,1,3,110,264,0,1,132,0,1.2,1,1
914,68,1,0,144,193,1,1,141,0,3.4,1,1
915,57,1,0,130,131,0,1,115,1,1.2,1,1
916,57,0,1,130,236,0,0,174,0,0.0,1,1
917,38,1,2,138,175,0,1,173,0,0.0,2,0

# Data slicing (dependent & independent variables)

In [9]:
x = heart.iloc[:,0:11].values
x

array([[40. ,  1. ,  1. , ...,  0. ,  0. ,  2. ],
       [49. ,  0. ,  2. , ...,  0. ,  1. ,  1. ],
       [37. ,  1. ,  1. , ...,  0. ,  0. ,  2. ],
       ...,
       [57. ,  1. ,  0. , ...,  1. ,  1.2,  1. ],
       [57. ,  0. ,  1. , ...,  0. ,  0. ,  1. ],
       [38. ,  1. ,  2. , ...,  0. ,  0. ,  2. ]])

In [10]:
y = heart.iloc[:,-1].values
y

array([0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0], dtype=int64)

# Model train_test_Split

In [11]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=0)

In [12]:
print(x_train.shape,x_test.shape,y_train.shape,y_test.shape)

(734, 11) (184, 11) (734,) (184,)

# Algorithm define

In [13]:
ann = tf.keras.models.Sequential()

# Input layer

In [14]:
ann.add(tf.keras.layers.Dense(units=6, activation="relu"))

# first hidden layer

In [15]:
ann.add(tf.keras.layers.Dense(units=6, activation="relu"))

# second hidden layer

In [16]:
ann.add(tf.keras.layers.Dense(units=6, activation="relu"))

# output layer

In [17]:
ann.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# compilation

In [18]:
ann.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy"])

In [19]:
ann.fit(x_train,y_train, batch_size=32, epochs=50)

Epoch 1/50
23/23 [==============================] - 2s 4ms/step - loss: 5.7158 - accuracy: 0.5504
Epoch 2/50
23/23 [==============================] - 0s 5ms/step - loss: 1.7814 - accuracy: 0.6417
Epoch 3/50
23/23 [==============================] - 0s 5ms/step - loss: 1.1198 - accuracy: 0.6703
Epoch 4/50
23/23 [==============================] - 0s 4ms/step - loss: 0.8631 - accuracy: 0.6676
Epoch 5/50
23/23 [==============================] - 0s 4ms/step - loss: 0.7457 - accuracy: 0.6621
Epoch 6/50
23/23 [==============================] - 0s 9ms/step - loss: 0.7068 - accuracy: 0.6608
Epoch 7/50
23/23 [==============================] - 0s 6ms/step - loss: 0.6821 - accuracy: 0.6594
Epoch 8/50
23/23 [==============================] - 0s 7ms/step - loss: 0.6630 - accuracy: 0.6594
Epoch 9/50
23/23 [==============================] - 0s 5ms/step - loss: 0.6520 - accuracy: 0.6649
Epoch 10/50
23/23 [==============================] - 0s 5ms/step - loss: 0.6373 - accuracy: 0.6662
Epoch 11/50
23/23 [==============================] - 0s 11ms/step - loss: 0.6271 - accuracy: 0.6662
Epoch 12/50
23/23 [==============================] - 0s 8ms/step - loss: 0.6233 - accuracy: 0.6730
Epoch 13/50
23/23 [==============================] - 0s 9ms/step - loss: 0.6232 - accuracy: 0.6757
Epoch 14/50
23/23 [==============================] - 0s 5ms/step - loss: 0.6173 - accuracy: 0.6785
Epoch 15/50
23/23 [==============================] - 0s 5ms/step - loss: 0.6164 - accuracy: 0.6866
Epoch 16/50
23/23 [==============================] - 0s 7ms/step - loss: 0.6124 - accuracy: 0.6853
Epoch 17/50
23/23 [==============================] - 0s 4ms/step - loss: 0.6100 - accuracy: 0.6853
Epoch 18/50
23/23 [==============================] - 0s 6ms/step - loss: 0.6062 - accuracy: 0.6935
Epoch 19/50
23/23 [==============================] - 0s 6ms/step - loss: 0.6047 - accuracy: 0.6907
Epoch 20/50
23/23 [==============================] - 0s 5ms/step - loss: 0.6024 - accuracy: 0.6894
Epoch 21/50
23/23 [==============================] - 0s 5ms/step - loss: 0.6007 - accuracy: 0.6935
Epoch 22/50
23/23 [==============================] - 0s 5ms/step - loss: 0.5974 - accuracy: 0.6948
Epoch 23/50
23/23 [==============================] - 0s 7ms/step - loss: 0.5973 - accuracy: 0.6989
Epoch 24/50
23/23 [==============================] - 0s 6ms/step - loss: 0.5945 - accuracy: 0.6975
Epoch 25/50
23/23 [==============================] - 0s 5ms/step - loss: 0.5915 - accuracy: 0.7016
Epoch 26/50
23/23 [==============================] - 0s 6ms/step - loss: 0.5919 - accuracy: 0.7003
Epoch 27/50
23/23 [==============================] - 0s 5ms/step - loss: 0.5925 - accuracy: 0.6975
Epoch 28/50
23/23 [==============================] - 0s 4ms/step - loss: 0.5873 - accuracy: 0.7084
Epoch 29/50
23/23 [==============================] - 0s 4ms/step - loss: 0.5880 - accuracy: 0.7112
Epoch 30/50
23/23 [==============================] - 0s 5ms/step - loss: 0.5888 - accuracy: 0.7125
Epoch 31/50
23/23 [==============================] - 0s 6ms/step - loss: 0.5858 - accuracy: 0.7180
Epoch 32/50
23/23 [==============================] - 0s 8ms/step - loss: 0.5837 - accuracy: 0.7125
Epoch 33/50
23/23 [==============================] - 0s 7ms/step - loss: 0.5830 - accuracy: 0.7166
Epoch 34/50
23/23 [==============================] - 0s 6ms/step - loss: 0.5832 - accuracy: 0.7207
Epoch 35/50
23/23 [==============================] - 0s 7ms/step - loss: 0.5873 - accuracy: 0.7193
Epoch 36/50
23/23 [==============================] - 0s 7ms/step - loss: 0.5777 - accuracy: 0.7193
Epoch 37/50
23/23 [==============================] - 0s 4ms/step - loss: 0.5834 - accuracy: 0.7084
Epoch 38/50
23/23 [==============================] - 0s 6ms/step - loss: 0.5818 - accuracy: 0.7330
Epoch 39/50
23/23 [==============================] - 0s 6ms/step - loss: 0.5820 - accuracy: 0.7125
Epoch 40/50
23/23 [==============================] - 0s 7ms/step - loss: 0.5819 - accuracy: 0.7166
Epoch 41/50
23/23 [==============================] - 0s 4ms/step - loss: 0.5804 - accuracy: 0.7262
Epoch 42/50
23/23 [==============================] - 0s 4ms/step - loss: 0.5768 - accuracy: 0.7193
Epoch 43/50
23/23 [==============================] - 0s 5ms/step - loss: 0.5827 - accuracy: 0.7166
Epoch 44/50
23/23 [==============================] - 0s 7ms/step - loss: 0.5788 - accuracy: 0.7221
Epoch 45/50
23/23 [==============================] - 0s 5ms/step - loss: 0.5768 - accuracy: 0.7248
Epoch 46/50
23/23 [==============================] - 0s 5ms/step - loss: 0.5751 - accuracy: 0.7289
Epoch 47/50
23/23 [==============================] - 0s 5ms/step - loss: 0.5734 - accuracy: 0.7248
Epoch 48/50
23/23 [==============================] - 0s 4ms/step - loss: 0.5741 - accuracy: 0.7316
Epoch 49/50
23/23 [==============================] - 0s 10ms/step - loss: 0.5738 - accuracy: 0.7289
Epoch 50/50
23/23 [==============================] - 0s 7ms/step - loss: 0.5720 - accuracy: 0.7262

# prediction

In [20]:
y_pred = ann.predict(x_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [1 0]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [0 1]
 [1 1]
 [1 0]
 [1 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [0 1]
 [1 1]
 [0 0]
 [1 0]
 [1 1]
 [1 1]
 [0 0]
 [0 1]
 [1 0]
 [1 1]
 [0 0]
 [0 1]
 [1 1]
 [0 1]
 [0 0]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 1]
 [1 1]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [1 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [0 1]
 [1 0]
 [0 1]
 [0 0]
 [1 1]
 [0 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [0 1]
 [1 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [1 1]
 [1 0]
 [0 1]
 [0 1]
 [1 1]
 [1 0]
 [1 1]
 [1 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [1 0]
 [1 0]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [0 1]
 [1 0]
 [1 1]]

# Accuracy_score

In [21]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
ac = accuracy_score(y_pred,y_test)*100
cm = confusion_matrix(y_pred,y_test)
cr = classification_report(y_pred,y_test)

In [22]:
print(ac)

73.36956521739131

In [23]:
print(cm)

[[53 25]
 [24 82]]

In [24]:
print(cr)

              precision    recall  f1-score   support

       False       0.69      0.68      0.68        78
        True       0.77      0.77      0.77       106

    accuracy                           0.73       184
   macro avg       0.73      0.73      0.73       184
weighted avg       0.73      0.73      0.73       184