# Machine Learning Algorithm (KNearest Neighbors)

1. KNN is a Machine learning supervised algorithm.
2. KNN finds out nearest neighbors between two data points
3. It assumes similarity between new class and avaliable class and the new class into the category that most similar to            available categories
4. It Uses binary as well as multi-categorical data

# Import Libraries

In [33]:
import numpy as np
import pandas as pd

# Data Loading

weather Australia data prediction

In [34]:
weather = pd.read_csv(r"C:\Users\Kajal\Desktop\ssd\Desktop\dataset work November\datasets\weatherAUS.csv")
weather

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,2008-12-01,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0,W,...,71.0,22.0,1007.7,1007.1,8.0,NaN,16.9,21.8,No,No
1,2008-12-02,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0,NNW,...,44.0,25.0,1010.6,1007.8,NaN,NaN,17.2,24.3,No,No
2,2008-12-03,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0,W,...,38.0,30.0,1007.6,1008.7,NaN,2.0,21.0,23.2,No,No
3,2008-12-04,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0,SE,...,45.0,16.0,1017.6,1012.8,NaN,NaN,18.1,26.5,No,No
4,2008-12-05,Albury,17.5,32.3,1.0,NaN,NaN,W,41.0,ENE,...,82.0,33.0,1010.8,1006.0,7.0,8.0,17.8,29.7,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145455,2017-06-21,Uluru,2.8,23.4,0.0,NaN,NaN,E,31.0,SE,...,51.0,24.0,1024.6,1020.3,NaN,NaN,10.1,22.4,No,No
145456,2017-06-22,Uluru,3.6,25.3,0.0,NaN,NaN,NNW,22.0,SE,...,56.0,21.0,1023.5,1019.1,NaN,NaN,10.9,24.5,No,No
145457,2017-06-23,Uluru,5.4,26.9,0.0,NaN,NaN,N,37.0,SE,...,53.0,24.0,1021.0,1016.8,NaN,NaN,12.5,26.1,No,No
145458,2017-06-24,Uluru,7.8,27.0,0.0,NaN,NaN,SE,28.0,SSE,...,51.0,24.0,1019.4,1016.5,3.0,2.0,15.1,26.0,No,No
145459,2017-06-25,Uluru,14.9,NaN,0.0,NaN,NaN,NaN,NaN,ESE,...,62.0,36.0,1020.2,1017.9,8.0,8.0,15.0,20.9,No,NaN

# info

In [35]:
weather.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145460 entries, 0 to 145459
Data columns (total 23 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Date           145460 non-null  object
 1   Location       145460 non-null  object
 2   MinTemp        143975 non-null  float64
 3   MaxTemp        144199 non-null  float64
 4   Rainfall       142199 non-null  float64
 5   Evaporation    82670 non-null   float64
 6   Sunshine       75625 non-null   float64
 7   WindGustDir    135134 non-null  object
 8   WindGustSpeed  135197 non-null  float64
 9   WindDir9am     134894 non-null  object
 10  WindDir3pm     141232 non-null  object
 11  WindSpeed9am   143693 non-null  float64
 12  WindSpeed3pm   142398 non-null  float64
 13  Humidity9am    142806 non-null  float64
 14  Humidity3pm    140953 non-null  float64
 15  Pressure9am    130395 non-null  float64
 16  Pressure3pm    130432 non-null  float64
 17  Cloud9am       89572 non-null   float64
 18  Cloud3pm       86102 non-null   float64
 19  Temp9am        143693 non-null  float64
 20  Temp3pm        141851 non-null  float64
 21  RainToday      142199 non-null  object
 22  RainTomorrow   142193 non-null  object
dtypes: float64(16), object(7)
memory usage: 25.5+ MB

# describe

In [36]:
weather.describe()

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm
count,143975.000000,144199.000000,142199.000000,82670.000000,75625.000000,135197.000000,143693.000000,142398.000000,142806.000000,140953.000000,130395.00000,130432.000000,89572.000000,86102.000000,143693.000000,141851.00000
mean,12.194034,23.221348,2.360918,5.468232,7.611178,40.035230,14.043426,18.662657,68.880831,51.539116,1017.64994,1015.255889,4.447461,4.509930,16.990631,21.68339
std,6.398495,7.119049,8.478060,4.193704,3.785483,13.607062,8.915375,8.809800,19.029164,20.795902,7.10653,7.037414,2.887159,2.720357,6.488753,6.93665
min,-8.500000,-4.800000,0.000000,0.000000,0.000000,6.000000,0.000000,0.000000,0.000000,0.000000,980.50000,977.100000,0.000000,0.000000,-7.200000,-5.40000
25%,7.600000,17.900000,0.000000,2.600000,4.800000,31.000000,7.000000,13.000000,57.000000,37.000000,1012.90000,1010.400000,1.000000,2.000000,12.300000,16.60000
50%,12.000000,22.600000,0.000000,4.800000,8.400000,39.000000,13.000000,19.000000,70.000000,52.000000,1017.60000,1015.200000,5.000000,5.000000,16.700000,21.10000
75%,16.900000,28.200000,0.800000,7.400000,10.600000,48.000000,19.000000,24.000000,83.000000,66.000000,1022.40000,1020.000000,7.000000,7.000000,21.600000,26.40000
max,33.900000,48.100000,371.000000,145.000000,14.500000,135.000000,130.000000,87.000000,100.000000,100.000000,1041.00000,1039.600000,9.000000,9.000000,40.200000,46.70000

# check null values using isnull().any()  "OR"  isnull().sum()

In [5]:
weather.isnull().any()

Date             False
Location         False
MinTemp           True
MaxTemp           True
Rainfall          True
Evaporation       True
Sunshine          True
WindGustDir       True
WindGustSpeed     True
WindDir9am        True
WindDir3pm        True
WindSpeed9am      True
WindSpeed3pm      True
Humidity9am       True
Humidity3pm       True
Pressure9am       True
Pressure3pm       True
Cloud9am          True
Cloud3pm          True
Temp9am           True
Temp3pm           True
RainToday         True
RainTomorrow      True
dtype: bool

In [6]:
weather.isnull().sum()

Date                 0
Location             0
MinTemp           1485
MaxTemp           1261
Rainfall          3261
Evaporation      62790
Sunshine         69835
WindGustDir      10326
WindGustSpeed    10263
WindDir9am       10566
WindDir3pm        4228
WindSpeed9am      1767
WindSpeed3pm      3062
Humidity9am       2654
Humidity3pm       4507
Pressure9am      15065
Pressure3pm      15028
Cloud9am         55888
Cloud3pm         59358
Temp9am           1767
Temp3pm           3609
RainToday         3261
RainTomorrow      3267
dtype: int64

In [7]:
min_T = weather["MinTemp"].mean()
min_T

12.19403438096892

In [8]:
max_T = weather["MaxTemp"].mean()
max_T

23.22134827564685

In [9]:
rain_fall = weather["Rainfall"].mean()
rain_fall

2.3609181499166656

In [10]:
evapo = weather["Evaporation"].mean()
evapo

5.468231522922462

In [11]:
sun_shine = weather["Sunshine"].mean()
sun_shine

7.6111775206611565

In [12]:
wind_gustspeed = weather["WindGustSpeed"].mean()
wind_gustspeed

40.03523007167319

In [13]:
humidity_9am = weather["Humidity9am"].mean()
humidity_9am

68.88083133761887

In [14]:
humidity_3pm = weather["Humidity3pm"].mean()
humidity_3pm

51.5391158755046

In [15]:
press_9am = weather["Pressure9am"].mean()
press_9am

1017.6499397983052

In [16]:
cloud_9am = weather["Cloud9am"].mean()
cloud_9am

4.4474612602152455

In [17]:
cloud_3pm = weather["Cloud3pm"].mean()
cloud_3pm

4.509930082924903

In [18]:
temp_9am = weather["Temp9am"].mean()
temp_9am

16.990631415587398

In [19]:
temp_3pm = weather["Temp3pm"].mean()
temp_3pm

21.68339031800974

# Replace Null values using fillna function

In [20]:
weather["MinTemp"].fillna(min_T,inplace=True)
weather["MaxTemp"].fillna(max_T,inplace=True)
weather["Rainfall"].fillna(rain_fall,inplace=True)
weather["Evaporation"].fillna(evapo,inplace=True)
weather["Sunshine"].fillna(sun_shine,inplace=True)
weather["WindGustSpeed"].fillna(wind_gustspeed,inplace=True)
weather["Humidity9am"].fillna(humidity_9am,inplace=True)
weather["Humidity3pm"].fillna(humidity_3pm,inplace=True)
weather["Pressure9am"].fillna(press_9am,inplace=True)
weather["Cloud9am"].fillna(cloud_9am,inplace=True)
weather["Cloud3pm"].fillna(cloud_3pm,inplace=True)
weather["Temp9am"].fillna(temp_9am,inplace=True)
weather["Temp3pm"].fillna(temp_3pm,inplace=True)
weather["WindGustDir"].fillna("EE",inplace=True)
weather["WindDir9am"].fillna("AF",inplace=True)
weather["WindDir3pm"].fillna("SSS",inplace=True)
weather["WindSpeed9am"].fillna(200,inplace=True)
weather["WindSpeed3pm"].fillna(300,inplace=True)
weather["Pressure3pm"].fillna(100,inplace=True)
weather["RainToday"].fillna("EE",inplace=True)
weather["RainTomorrow"].fillna("EE",inplace=True)

In [21]:
weather

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,2008-12-01,Albury,13.4,22.900000,0.6,5.468232,7.611178,W,44.00000,W,...,71.0,22.0,1007.7,1007.1,8.000000,4.50993,16.9,21.8,No,No
1,2008-12-02,Albury,7.4,25.100000,0.0,5.468232,7.611178,WNW,44.00000,NNW,...,44.0,25.0,1010.6,1007.8,4.447461,4.50993,17.2,24.3,No,No
2,2008-12-03,Albury,12.9,25.700000,0.0,5.468232,7.611178,WSW,46.00000,W,...,38.0,30.0,1007.6,1008.7,4.447461,2.00000,21.0,23.2,No,No
3,2008-12-04,Albury,9.2,28.000000,0.0,5.468232,7.611178,NE,24.00000,SE,...,45.0,16.0,1017.6,1012.8,4.447461,4.50993,18.1,26.5,No,No
4,2008-12-05,Albury,17.5,32.300000,1.0,5.468232,7.611178,W,41.00000,ENE,...,82.0,33.0,1010.8,1006.0,7.000000,8.00000,17.8,29.7,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145455,2017-06-21,Uluru,2.8,23.400000,0.0,5.468232,7.611178,E,31.00000,SE,...,51.0,24.0,1024.6,1020.3,4.447461,4.50993,10.1,22.4,No,No
145456,2017-06-22,Uluru,3.6,25.300000,0.0,5.468232,7.611178,NNW,22.00000,SE,...,56.0,21.0,1023.5,1019.1,4.447461,4.50993,10.9,24.5,No,No
145457,2017-06-23,Uluru,5.4,26.900000,0.0,5.468232,7.611178,N,37.00000,SE,...,53.0,24.0,1021.0,1016.8,4.447461,4.50993,12.5,26.1,No,No
145458,2017-06-24,Uluru,7.8,27.000000,0.0,5.468232,7.611178,SE,28.00000,SSE,...,51.0,24.0,1019.4,1016.5,3.000000,2.00000,15.1,26.0,No,No
145459,2017-06-25,Uluru,14.9,23.221348,0.0,5.468232,7.611178,EE,40.03523,ESE,...,62.0,36.0,1020.2,1017.9,8.000000,8.00000,15.0,20.9,No,EE

# Label Encoding (Convert the data string to numeric)

In [22]:
from sklearn.preprocessing import LabelEncoder
L1 = LabelEncoder()
weather["Location"] = L1.fit_transform(weather["Location"])
weather["WindGustDir"] = L1.fit_transform(weather["WindGustDir"])
weather["WindDir9am"] = L1.fit_transform(weather["WindDir9am"])
weather["WindDir3pm"] = L1.fit_transform(weather["WindDir3pm"])
weather["RainTomorrow"] = L1.fit_transform(weather["RainTomorrow"])

In [23]:
weather_1=weather.drop(columns=["Location","Date","RainToday"])
weather_1

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainTomorrow
0,13.4,22.900000,0.6,5.468232,7.611178,14,44.00000,14,15,20.0,24.0,71.0,22.0,1007.7,1007.1,8.000000,4.50993,16.9,21.8,1
1,7.4,25.100000,0.0,5.468232,7.611178,15,44.00000,7,16,4.0,22.0,44.0,25.0,1010.6,1007.8,4.447461,4.50993,17.2,24.3,1
2,12.9,25.700000,0.0,5.468232,7.611178,16,46.00000,14,16,19.0,26.0,38.0,30.0,1007.6,1008.7,4.447461,2.00000,21.0,23.2,1
3,9.2,28.000000,0.0,5.468232,7.611178,5,24.00000,10,0,11.0,9.0,45.0,16.0,1017.6,1012.8,4.447461,4.50993,18.1,26.5,1
4,17.5,32.300000,1.0,5.468232,7.611178,14,41.00000,2,7,7.0,20.0,82.0,33.0,1010.8,1006.0,7.000000,8.00000,17.8,29.7,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145455,2.8,23.400000,0.0,5.468232,7.611178,0,31.00000,10,1,13.0,11.0,51.0,24.0,1024.6,1020.3,4.447461,4.50993,10.1,22.4,1
145456,3.6,25.300000,0.0,5.468232,7.611178,7,22.00000,10,3,13.0,9.0,56.0,21.0,1023.5,1019.1,4.447461,4.50993,10.9,24.5,1
145457,5.4,26.900000,0.0,5.468232,7.611178,4,37.00000,10,15,9.0,9.0,53.0,24.0,1021.0,1016.8,4.447461,4.50993,12.5,26.1,1
145458,7.8,27.000000,0.0,5.468232,7.611178,10,28.00000,11,3,13.0,7.0,51.0,24.0,1019.4,1016.5,3.000000,2.00000,15.1,26.0,1
145459,14.9,23.221348,0.0,5.468232,7.611178,1,40.03523,3,2,17.0,17.0,62.0,36.0,1020.2,1017.9,8.000000,8.00000,15.0,20.9,0

In [28]:
weather_1["RainTomorrow"].unique()

array([1, 2, 0])

# Data slicing into dependent & independent variables

In [24]:
x = weather_1.iloc[:,0:19]
x

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm
0,13.4,22.900000,0.6,5.468232,7.611178,14,44.00000,14,15,20.0,24.0,71.0,22.0,1007.7,1007.1,8.000000,4.50993,16.9,21.8
1,7.4,25.100000,0.0,5.468232,7.611178,15,44.00000,7,16,4.0,22.0,44.0,25.0,1010.6,1007.8,4.447461,4.50993,17.2,24.3
2,12.9,25.700000,0.0,5.468232,7.611178,16,46.00000,14,16,19.0,26.0,38.0,30.0,1007.6,1008.7,4.447461,2.00000,21.0,23.2
3,9.2,28.000000,0.0,5.468232,7.611178,5,24.00000,10,0,11.0,9.0,45.0,16.0,1017.6,1012.8,4.447461,4.50993,18.1,26.5
4,17.5,32.300000,1.0,5.468232,7.611178,14,41.00000,2,7,7.0,20.0,82.0,33.0,1010.8,1006.0,7.000000,8.00000,17.8,29.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145455,2.8,23.400000,0.0,5.468232,7.611178,0,31.00000,10,1,13.0,11.0,51.0,24.0,1024.6,1020.3,4.447461,4.50993,10.1,22.4
145456,3.6,25.300000,0.0,5.468232,7.611178,7,22.00000,10,3,13.0,9.0,56.0,21.0,1023.5,1019.1,4.447461,4.50993,10.9,24.5
145457,5.4,26.900000,0.0,5.468232,7.611178,4,37.00000,10,15,9.0,9.0,53.0,24.0,1021.0,1016.8,4.447461,4.50993,12.5,26.1
145458,7.8,27.000000,0.0,5.468232,7.611178,10,28.00000,11,3,13.0,7.0,51.0,24.0,1019.4,1016.5,3.000000,2.00000,15.1,26.0
145459,14.9,23.221348,0.0,5.468232,7.611178,1,40.03523,3,2,17.0,17.0,62.0,36.0,1020.2,1017.9,8.000000,8.00000,15.0,20.9

In [25]:
y = weather_1.iloc[:,-1]
y

0         1
1         1
2         1
3         1
4         1
         ..
145455    1
145456    1
145457    1
145458    1
145459    0
Name: RainTomorrow, Length: 145460, dtype: int32

# Model train_test_split

In [26]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size=0.4, random_state=0)

In [27]:
print(x_train.shape,x_test.shape,y_train.shape,y_test.shape)

(87276, 19) (58184, 19) (87276,) (58184,)

# Algorithm define

In [29]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5,metric='minkowski',p=2)
classifier.fit(x_train,y_train)

KNeighborsClassifier()

# Prediction

In [30]:
y_pred = classifier.predict(x_test)
y_pred

array([1, 1, 1, ..., 1, 2, 1])

# Accuracy_score,Confusion_matrix,Classification_report

In [31]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
ac = accuracy_score(y_pred,y_test)*100
cm = confusion_matrix(y_pred,y_test)
cr = classification_report(y_pred,y_test)
print(ac)
print("************************************")

print(cm)
print("************************************")

print(cr)

81.9177093358999
************************************
[[  298   108    63]
 [  815 41178  6516]
 [  173  2846  6187]]
************************************
              precision    recall  f1-score   support

           0       0.23      0.64      0.34       469
           1       0.93      0.85      0.89     48509
           2       0.48      0.67      0.56      9206

    accuracy                           0.82     58184
   macro avg       0.55      0.72      0.60     58184
weighted avg       0.86      0.82      0.83     58184