# Multiple Linear Regression

1. Linear Regression:
   Types Of Linear Regression is
   
   a) Simple Linear Regression
   b) Multiple Linear Regression
   
   a)Simple Linear Regression:
            If you have One dependent and One independent variable is called Simple Linear Regression.
            
   b)Multiple Linear Regression:
            If you have one dependent and multiple independent variables is calles Multiple Linear Regression.

# Import Libraries

In [1]:
import numpy as np
import pandas as pd

# Data Loading

In [2]:
car = pd.read_csv(r"C:\Users\Kajal\Desktop\ssd\Desktop\dataset work November\datasets\CarPrice.csv")

In [3]:
car

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201,-1,volvo 145e (sw),gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845.0
201,202,-1,volvo 144ea,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045.0
202,203,-1,volvo 244dl,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485.0
203,204,-1,volvo 246,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470.0
204,205,-1,volvo 264gl,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625.0

# info

In [4]:
car.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   car_ID            205 non-null    int64
 1   symboling         205 non-null    int64
 2   CarName           205 non-null    object
 3   fueltype          205 non-null    object
 4   aspiration        205 non-null    object
 5   doornumber        205 non-null    object
 6   carbody           205 non-null    object
 7   drivewheel        205 non-null    object
 8   enginelocation    205 non-null    object
 9   wheelbase         205 non-null    float64
 10  carlength         205 non-null    float64
 11  carwidth          205 non-null    float64
 12  carheight         205 non-null    float64
 13  curbweight        205 non-null    int64
 14  enginetype        205 non-null    object
 15  cylindernumber    205 non-null    object
 16  enginesize        205 non-null    int64
 17  fuelsystem        205 non-null    object
 18  boreratio         205 non-null    float64
 19  stroke            205 non-null    float64
 20  compressionratio  205 non-null    float64
 21  horsepower        205 non-null    int64
 22  peakrpm           205 non-null    int64
 23  citympg           205 non-null    int64
 24  highwaympg        205 non-null    int64
 25  price             205 non-null    float64
dtypes: float64(8), int64(8), object(10)
memory usage: 41.8+ KB

# describe

In [5]:
car.describe()

,car_ID,symboling,wheelbase,carlength,carwidth,carheight,curbweight,enginesize,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
count,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000
mean,103.000000,0.834146,98.756585,174.049268,65.907805,53.724878,2555.565854,126.907317,3.329756,3.255415,10.142537,104.117073,5125.121951,25.219512,30.751220,13276.710571
std,59.322565,1.245307,6.021776,12.337289,2.145204,2.443522,520.680204,41.642693,0.270844,0.313597,3.972040,39.544167,476.985643,6.542142,6.886443,7988.852332
min,1.000000,-2.000000,86.600000,141.100000,60.300000,47.800000,1488.000000,61.000000,2.540000,2.070000,7.000000,48.000000,4150.000000,13.000000,16.000000,5118.000000
25%,52.000000,0.000000,94.500000,166.300000,64.100000,52.000000,2145.000000,97.000000,3.150000,3.110000,8.600000,70.000000,4800.000000,19.000000,25.000000,7788.000000
50%,103.000000,1.000000,97.000000,173.200000,65.500000,54.100000,2414.000000,120.000000,3.310000,3.290000,9.000000,95.000000,5200.000000,24.000000,30.000000,10295.000000
75%,154.000000,2.000000,102.400000,183.100000,66.900000,55.500000,2935.000000,141.000000,3.580000,3.410000,9.400000,116.000000,5500.000000,30.000000,34.000000,16503.000000
max,205.000000,3.000000,120.900000,208.100000,72.300000,59.800000,4066.000000,326.000000,3.940000,4.170000,23.000000,288.000000,6600.000000,49.000000,54.000000,45400.000000

# Checking null values

In [6]:
car.isnull().any()

car_ID              False
symboling           False
CarName             False
fueltype            False
aspiration          False
doornumber          False
carbody             False
drivewheel          False
enginelocation      False
wheelbase           False
carlength           False
carwidth            False
carheight           False
curbweight          False
enginetype          False
cylindernumber      False
enginesize          False
fuelsystem          False
boreratio           False
stroke              False
compressionratio    False
horsepower          False
peakrpm             False
citympg             False
highwaympg          False
price               False
dtype: bool

In [7]:
car.isnull().sum()

car_ID              0
symboling           0
CarName             0
fueltype            0
aspiration          0
doornumber          0
carbody             0
drivewheel          0
enginelocation      0
wheelbase           0
carlength           0
carwidth            0
carheight           0
curbweight          0
enginetype          0
cylindernumber      0
enginesize          0
fuelsystem          0
boreratio           0
stroke              0
compressionratio    0
horsepower          0
peakrpm             0
citympg             0
highwaympg          0
price               0
dtype: int64

# Label Encoding (Convert data string to numeric)

In [8]:
from sklearn.preprocessing import LabelEncoder
L1 = LabelEncoder()
car["CarName"]=L1.fit_transform(car["CarName"])
car["fueltype"]=L1.fit_transform(car["fueltype"])
car["aspiration"]=L1.fit_transform(car["aspiration"])
car["doornumber"]=L1.fit_transform(car["doornumber"])
car["carbody"]=L1.fit_transform(car["carbody"])
car["drivewheel"]=L1.fit_transform(car["drivewheel"])
car["enginelocation"]=L1.fit_transform(car["enginelocation"])
car["enginetype"]=L1.fit_transform(car["enginetype"])
car["cylindernumber"]=L1.fit_transform(car["cylindernumber"])
car["fuelsystem"]=L1.fit_transform(car["fuelsystem"])

In [9]:
car

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,2,1,0,1,0,2,0,88.6,...,130,5,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,3,1,0,1,0,2,0,88.6,...,130,5,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,1,1,0,1,2,2,0,94.5,...,152,5,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,4,1,0,0,3,1,0,99.8,...,109,5,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,5,1,0,0,3,0,0,99.4,...,136,5,3.19,3.40,8.0,115,5500,18,22,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201,-1,139,1,0,0,3,2,0,109.1,...,141,5,3.78,3.15,9.5,114,5400,23,28,16845.0
201,202,-1,138,1,1,0,3,2,0,109.1,...,141,5,3.78,3.15,8.7,160,5300,19,25,19045.0
202,203,-1,140,1,0,0,3,2,0,109.1,...,173,5,3.58,2.87,8.8,134,5500,18,23,21485.0
203,204,-1,142,0,1,0,3,2,0,109.1,...,145,3,3.01,3.40,23.0,106,4800,26,27,22470.0
204,205,-1,143,1,1,0,3,2,0,109.1,...,141,5,3.78,3.15,9.5,114,5400,19,25,22625.0

# Slice data into dependent and indenpendent variable

# 1. Independent variables

In [10]:
x = car.iloc[:,0:25]
x

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,cylindernumber,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg
0,1,3,2,1,0,1,0,2,0,88.6,...,2,130,5,3.47,2.68,9.0,111,5000,21,27
1,2,3,3,1,0,1,0,2,0,88.6,...,2,130,5,3.47,2.68,9.0,111,5000,21,27
2,3,1,1,1,0,1,2,2,0,94.5,...,3,152,5,2.68,3.47,9.0,154,5000,19,26
3,4,2,4,1,0,0,3,1,0,99.8,...,2,109,5,3.19,3.40,10.0,102,5500,24,30
4,5,2,5,1,0,0,3,0,0,99.4,...,1,136,5,3.19,3.40,8.0,115,5500,18,22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,201,-1,139,1,0,0,3,2,0,109.1,...,2,141,5,3.78,3.15,9.5,114,5400,23,28
201,202,-1,138,1,1,0,3,2,0,109.1,...,2,141,5,3.78,3.15,8.7,160,5300,19,25
202,203,-1,140,1,0,0,3,2,0,109.1,...,3,173,5,3.58,2.87,8.8,134,5500,18,23
203,204,-1,142,0,1,0,3,2,0,109.1,...,3,145,3,3.01,3.40,23.0,106,4800,26,27
204,205,-1,143,1,1,0,3,2,0,109.1,...,2,141,5,3.78,3.15,9.5,114,5400,19,25

# 2. Dependent Variable

In [11]:
y = car.iloc[:,-1]
y

0      13495.0
1      16500.0
2      16500.0
3      13950.0
4      17450.0
        ...
200    16845.0
201    19045.0
202    21485.0
203    22470.0
204    22625.0
Name: price, Length: 205, dtype: float64

# Model training and testing

In [12]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size=0.2, random_state=0)

In [13]:
x_train

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,cylindernumber,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg
4,5,2,5,1,0,0,3,0,0,99.4,...,1,136,5,3.19,3.40,8.0,115,5500,18,22
71,72,-1,20,1,0,0,3,2,0,115.6,...,0,234,5,3.46,3.10,8.3,155,4750,16,18
134,135,3,103,1,0,1,2,1,0,99.1,...,2,121,5,2.54,2.07,9.3,110,5250,21,28
145,146,0,109,1,1,0,3,0,0,97.0,...,2,108,5,3.62,2.64,7.7,111,4800,24,29
122,123,1,91,1,0,0,3,1,0,93.7,...,2,98,1,2.97,3.23,9.4,68,5500,31,38
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,68,-1,19,0,1,0,3,2,0,110.0,...,1,183,3,3.58,3.64,21.5,123,4350,22,25
192,193,0,135,0,1,0,3,1,0,100.4,...,2,97,3,3.01,3.40,23.0,68,4500,33,38
117,118,0,88,1,1,0,3,2,0,108.0,...,2,134,5,3.61,3.21,7.0,142,5600,18,24
47,48,0,49,1,0,0,3,2,0,113.0,...,3,258,5,3.63,4.17,8.1,176,4750,15,19
172,173,2,124,1,0,1,0,2,0,98.4,...,2,146,5,3.62,3.50,9.3,116,4800,24,30

In [14]:
x_test

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,cylindernumber,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg
52,53,1,61,1,0,1,2,1,0,93.1,...,2,91,1,3.03,3.150,9.0,68,5000,31,38
181,182,-1,128,1,0,0,4,2,0,104.5,...,3,161,5,3.27,3.350,9.2,156,5200,19,24
5,6,2,9,1,0,1,3,1,0,99.8,...,1,136,5,3.19,3.400,8.5,110,5500,19,25
18,19,2,24,1,0,1,2,1,0,88.4,...,4,61,1,2.91,3.030,9.5,48,5100,47,53
188,189,2,132,1,0,0,3,1,0,97.3,...,2,109,5,3.19,3.400,10.0,100,5500,26,32
170,171,2,127,1,0,1,1,2,0,98.4,...,2,146,5,3.62,3.500,9.3,116,4800,24,30
76,77,2,65,1,0,1,2,1,0,93.7,...,2,92,1,2.97,3.230,9.4,68,5500,37,41
154,155,0,117,1,0,0,4,0,0,95.7,...,2,92,1,3.05,3.030,9.0,62,4800,27,32
104,105,3,82,1,0,1,2,2,0,91.3,...,3,181,5,3.43,3.270,9.0,160,5200,19,25
33,34,1,37,1,0,1,2,1,0,93.7,...,2,92,0,2.91,3.410,9.2,76,6000,30,34
12,13,0,11,1,0,1,3,2,0,101.2,...,3,164,5,3.31,3.190,9.0,121,4250,21,28
129,130,1,97,1,0,1,2,2,0,98.4,...,0,203,5,3.94,3.110,10.0,288,5750,17,28
55,56,3,53,1,0,1,2,2,0,95.3,...,6,70,2,3.33,3.255,9.4,101,6000,17,23
66,67,0,60,0,0,0,3,2,0,104.9,...,2,134,3,3.43,3.640,22.0,72,4200,31,39
45,46,0,46,1,0,0,3,1,0,94.5,...,2,90,1,3.03,3.110,9.6,70,5400,38,43
169,170,2,126,1,0,1,2,2,0,98.4,...,2,146,5,3.62,3.500,9.3,116,4800,24,30
130,131,0,99,1,0,0,4,1,0,96.1,...,2,132,5,3.46,3.900,8.7,90,5100,23,31
7,8,1,7,1,0,0,4,1,0,105.8,...,1,136,5,3.19,3.400,8.5,110,5500,19,25
37,38,0,36,1,0,1,2,1,0,96.5,...,2,110,0,3.15,3.580,9.0,86,5800,27,33
152,153,1,116,1,0,0,2,1,0,95.7,...,2,92,1,3.05,3.030,9.0,62,4800,31,38
80,81,3,66,1,1,1,2,1,0,96.3,...,2,110,6,3.17,3.460,7.5,116,5500,23,30
111,112,0,85,1,0,0,3,2,0,107.9,...,2,120,5,3.46,2.190,8.4,95,5000,19,24
131,132,2,100,1,0,1,2,1,0,96.1,...,2,132,5,3.46,3.900,8.7,90,5100,23,31
171,172,2,115,1,0,1,2,2,0,98.4,...,2,146,5,3.62,3.500,9.3,116,4800,24,30
179,180,3,120,1,0,1,2,2,0,102.9,...,3,171,5,3.27,3.350,9.3,161,5200,19,24
138,139,2,104,1,0,1,2,1,0,93.7,...,2,97,1,3.62,2.360,9.0,69,4900,31,36
156,157,0,125,1,0,0,3,1,0,95.7,...,2,98,1,3.19,3.030,9.0,70,4800,30,37
113,114,0,85,1,0,0,4,2,0,114.2,...,2,120,5,3.46,2.190,8.4,95,5000,19,24
161,162,0,115,1,0,0,2,1,0,95.7,...,2,98,1,3.19,3.030,9.0,70,4800,28,34
89,90,1,0,1,0,1,3,1,0,94.5,...,2,97,1,3.15,3.290,9.4,69,5200,31,37
183,184,2,130,1,0,1,3,1,0,97.3,...,2,109,5,3.19,3.400,9.0,85,5250,27,34
193,194,0,132,1,0,0,4,1,0,100.4,...,2,109,5,3.19,3.400,9.0,88,5500,25,31
125,126,3,98,1,0,1,2,2,0,94.5,...,2,151,5,3.94,3.110,9.5,143,5500,19,27
173,174,-1,115,1,0,0,3,1,0,102.4,...,2,122,5,3.31,3.540,8.7,92,4200,29,34
92,93,1,76,1,0,0,3,1,0,94.5,...,2,97,1,3.15,3.290,9.4,69,5200,31,37
16,17,0,14,1,0,1,3,2,0,103.5,...,3,209,5,3.62,3.390,8.0,182,5400,16,22
189,190,3,145,1,0,1,0,1,0,94.5,...,2,109,5,3.19,3.400,8.5,90,5500,24,29
136,137,3,102,1,1,1,2,1,0,99.1,...,2,121,5,3.54,3.070,9.0,160,5500,19,26
22,23,1,27,1,0,1,2,1,0,93.7,...,2,90,1,2.97,3.230,9.4,68,5500,31,38
74,75,1,21,1,0,1,1,2,0,112.0,...,0,304,5,3.80,3.350,8.0,184,4500,14,16
44,45,1,45,1,0,1,3,1,0,94.5,...,2,90,1,3.03,3.110,9.6,70,5400,38,43

In [15]:
a = x_test[["carlength","carwidth","carheight","curbweight","enginetype","cylindernumber"]]
a

     carlength  carwidth  carheight  curbweight  enginetype  cylindernumber
52       159.1      64.2       54.1        1905           3               2
181      187.8      66.5       54.1        3151           0               3
5        177.3      66.3       53.1        2507           3               1
18       141.1      60.3       53.2        1488           2               4
188      171.7      65.5       55.7        2300           3               2
170      176.2      65.6       52.0        2679           3               2
76       157.3      64.4       50.8        1918           3               2
154      169.7      63.6       59.1        2290           3               2
104      170.7      67.9       49.7        3071           5               3
33       150.0      64.0       52.6        1940           3               2
12       176.8      64.8       54.3        2710           3               3
129      175.7      72.3       50.5        3366           1               0
55       169.0      65.7       49.6        2380           6               6
66       175.0      66.1       54.4        2700           3               2
45       155.9      63.6       52.0        1909           3               2
169      176.2      65.6       52.0        2551           3               2
130      181.5      66.5       55.2        2579           3               2
7        192.7      71.4       55.7        2954           3               1
37       167.5      65.2       53.3        2236           3               2
152      158.7      63.6       54.5        2015           3               2
80       173.0      65.4       49.4        2370           3               2
111      186.7      68.4       56.7        3075           2               2
131      176.8      66.6       50.5        2460           3               2
171      176.2      65.6       52.0        2714           3               2
179      183.5      67.7       52.0        3016           0               3
138      156.9      63.4       53.7        2050           4               2
156      166.3      64.4       53.0        2081           3               2
113      198.9      68.4       56.7        3285           2               2
161      166.3      64.4       52.8        2122           3               2
89       165.3      63.8       54.5        1889           3               2
183      171.7      65.5       55.7        2209           3               2
193      183.1      66.9       55.1        2563           3               2
125      168.9      68.3       50.2        2778           3               2
173      175.6      66.5       54.9        2326           3               2
92       165.3      63.8       54.5        1938           3               2
16       193.8      67.9       53.7        3380           3               3
189      159.3      64.2       55.6        2254           3               2
136      186.6      66.5       56.1        2808           0               2
22       157.3      63.8       50.8        1876           3               2
74       199.2      72.0       55.4        3715           5               0
44       155.9      63.6       52.0        1874           3               2

In [16]:
y_train

4      17450.0
71     34184.0
134    15040.0
145    11259.0
122     7609.0
        ...
67     25552.0
192    13845.0
117    18150.0
47     32250.0
172    17669.0
Name: price, Length: 164, dtype: float64

In [17]:
y_test

52      6795.0
181    15750.0
5      15250.0
18      5151.0
188     9995.0
170    11199.0
76      5389.0
154     7898.0
104    17199.0
33      6529.0
12     20970.0
129    31400.5
55     10945.0
66     18344.0
45      8916.5
169     9989.0
130     9295.0
7      18920.0
37      7895.0
152     6488.0
80      9959.0
111    15580.0
131     9895.0
171    11549.0
179    15998.0
138     5118.0
156     6938.0
113    16695.0
161     8358.0
89      5499.0
183     7975.0
193    12290.0
125    22018.0
173     8948.0
92      6849.0
16     41315.0
189    11595.0
136    18150.0
22      6377.0
74     45400.0
44      8916.5
Name: price, dtype: float64

# Algorithm define (Multiple Linear Regression)

In [18]:
from sklearn.linear_model import LinearRegression
classifier = LinearRegression()
classifier.fit(x_train,y_train)

LinearRegression()

# Prediction

In [19]:
y_pred = classifier.predict(x_test)
y_pred

array([ 4838.44522235, 17791.96485255, 13281.89609093,  4998.96824328,
       10145.09805948, 11915.56298093,  7273.91350059,  5302.00370191,
       19247.85292267,  7681.1179757 , 16926.20414232, 22395.57608963,
       11722.37286116, 11745.82880633,  7354.71531202, 10746.44662309,
        9274.35589895, 19962.65341746,  9821.30242199,  6823.28825805,
       10783.6507206 , 19569.8734405 ,  8837.165637  , 13041.23264335,
       20766.05674086,  7251.93589346,  5277.13134767, 20161.22996644,
        7839.02414733, 15627.06851337,  7976.30712281, 10992.10159328,
       15250.86625252, 10196.19171442,  6676.89929492, 24887.14041915,
        8302.61970031, 14947.21400519,  7032.40515667, 37792.92711347,
        6138.70544338])